PJI2/urls.py
from django.contrib import admin
from django.urls import path
from pji2app.views import home, form, create, view, edit, update, delete


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('form/', form, name='form'),
    path('create/', create, name='create'),
    path('view/<int:pk>/', view, name='view'),
    path('edit/<int:pk>/', edit, name='edit'),
    path('update/<int:pk>/', update, name='update'),
    path('delete/<int:pk>/', delete, name='delete')
]

pji2app/models.py
from django.db import models


class Cadastro(models.Model):
    inputEmpresa = models.CharField(max_length=255, null=True, blank=True)
    inputCNPJ = models.CharField(max_length=18, null=True, blank=True)
    inputEmail = models.EmailField(max_length=100, null=True, blank=True)
    inputTel = models.CharField(max_length=13, null=True, blank=True)
    inputCel = models.CharField(max_length=14, null=True, blank=True)
    inputAddress = models.CharField(max_length=255, null=True, blank=True)
    inputNumber = models.IntegerField(null=True, blank=True)
    inputAddress2 = models.CharField(max_length=100, null=True, blank=True)
    inputCEP = models.CharField(max_length=9, null=True, blank=True)
    inputCity = models.CharField(max_length=50, null=True, blank=True)
    inputEstado = models.CharField(max_length=20, null=True, blank=True)
    inputTipo = models.BooleanField(null=None, blank=None)

pji2app/forms.py
from django.forms import ModelForm
from pji2app.models import Cadastro


class CadastroForm(ModelForm):
    class Meta:
        model = Cadastro
        fields = ['inputEmpresa', 'inputCNPJ', 'inputEmail', 'inputTel', 'inputCel', 'inputAddress', 'inputNumber', 'inputAddress2', 'inputCEP', 'inputCity', 'inputEstado','inputTipo']
        #inputTipo define qual lado da cadeia de produção está a empresa: 'True' para produtor, 'False' para reciclador

pji2app/views.py
from django.shortcuts import render, redirect
from pji2app.forms import CadastroForm
from pji2app.models import Cadastro
from django.core.paginator import Paginator


def home(request):
    data = {}
    search = request.GET.get('search')
    if search:
        if tipo == "None":
            data['db'] = Cadastro.objects.filter(inputCity__icontains=search)
        else:
            data['db'] = Cadastro.objects.filter(inputCity__icontains=search, inputTipo=tipo)
    else:
        qry_data = Cadastro.objects.get_queryset().order_by(
            'id')  # Garante que o DB fornece um registro de cada vez, ordenado por Id
        paginator = Paginator(qry_data, 4)  # Exibe 4 registros do DB por página
        pages = request.GET.get('page')  # Captura qual é a página (page) selecionada no index.html pelo usuário
        data['db'] = paginator.get_page(pages)
    #   data['db'] = Cadastro.objects.all() ## Para buscar todos os registros do DB ## Linha para request sem paginação
    return render(request, 'index.html', data)


def form(request):
    data = {}
    data['form'] = CadastroForm()
    return render(request, 'form.html', data)


def create(request):
    form = CadastroForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('home')


def view(request, pk):
    data = {}
    data['db'] = Cadastro.objects.get(pk=pk)
    return render(request, 'view.html', data)


def edit(request, pk):
    data = {}
    data['db'] = Cadastro.objects.get(pk=pk)
    data['form'] = CadastroForm(instance=data['db'])
    return render(request, 'form.html', data)


def update(request, pk):
    data = {}
    data['db'] = Cadastro.objects.get(pk=pk)
    form = CadastroForm(request.POST or None, instance=data['db'])
    if form.is_valid():
        form.save()
        return redirect('home')


def delete(request, pk):
    db = Cadastro.objects.get(pk=pk)
    db.delete()
    return redirect('home')

pji2app/templates/form.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cadastramento</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
<div class="container-fluid col-12">
  <div class="jumbotron">
    <div class="col-8 m-auto pt-3 pb-3 text-center">
        <h1>CADASTRO DE ESTABELECIMENTO</h1>
    </div>

    <div class="col-8 m-auto pt-3 pb-3 text-center">
        <a href="/" class="btn btn-info">VOLTAR</a>
    </div>

    <div class="col-12 m-auto pt-3 pb-3 text-center">
        <!-- {{form.as_p}} linha para testar a exibição do formulario-->
        <div id="result">
        <form class="form" id="form" action="{% if db %}/update/{{db.id}}/{% else %}/create/{% endif %}" method="post">
            {% csrf_token %} <!-- comando do Django para garantir proteção ao formulário-->

            <div class="form-group mt-4">
                <input type="radio" id="restaurante" name="inputTipo" value="True">
                <label for="restaurante">Restaurante ou Similar</label><br>
                <input type="radio" id="cooperativa" name="inputTipo" value="False">
                <label for="cooperativa">Reciclador ou Similar</label>
            </div>
            <div class="form-group text-center">
            <div><label>Razão Social: </label> {{form.inputEmpresa}}</div>
            <div><label> CNPJ: </label> {{form.inputCNPJ}}</div>
            <div><label> Email: </label> {{form.inputEmail}}</div>
            <div><label>Telefone:</label> {{form.inputTel}}</div>
            <div><label>Celular:</label> {{form.inputCel}}</div>
            <div><label>Endereço:</label> {{form.inputAddress}}</div>
            <div><label>Número:</label> {{form.inputNumber}}</div>
            <div><label>Complemento:</label> {{form.inputAddress2}}</div>
            <div><label>CEP:</label> {{form.inputCEP}}</div>
            <div><label>Cidade:</label> {{form.inputCity}}</div>
            <div><label>Estado:</label> {{form.inputEstado}}</div>

            <input type="submit" class="btn btn-success" , value="SALVAR">
            </div>
        </form>
        </div>
    </div>

    {% load static %}
    {% block scripts %}
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'javascript.js' %}"></script>
    <script src="{% static 'jquery.mask.min.js' %}"></script>

    <script>
        $(document).ready(function(){
        $("#id_inputCEP").mask('00000-000');
        $("#id_inputTel").mask('(00)0000-0000');
        $("#id_inputCel").mask('(00)00000-0000');
        $('#id_inputCNPJ').mask('00.000.000/0000-00', {reverse: true});
        })
    </script>

    {% endblock %}
  </div>
</div>
</body>
</html>

pji2app/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Aplicativo PJI2APP</title>

</head>
<body>
<div class="container-fluid col-12">
  <div class="jumbotron">
    <div class="col-10 m-auto pb-3 text-center">
        <h2>CADASTRO DE PRODUTORES E RECICLADORES DE ÓLEO COMESTÍVEL USADO</h2>
        <h3>Página de Consulta de Estabelecimentos</h3></div>
      <div class="m-auto pt-4 pb-4 text-center ">
        <h4>Clique em CADASTRAR para inserir um novo estabelecimento</h4>
    </div>
    <div class="col-8 m-auto pt-3 pb-3 text-center">
        <a href="/form" class="btn btn-success">CADASTRAR</a> <!-- clicando em ADICIONAR, chama a página 'form' -->
    </div>
    <div>
        <form method="get">
            <div class="container-fluid col-10 pt-4 pb-3 text-center"><h2>Faça a busca por estabelecimento e por município</h2></div>
            <div class=" container-fluid col-3 m-auto text-left">
            <input type="radio" id="produtor" name="inputTipo" value="True">
            <label for="produtor">Busca Restaurantes e Similares</label><br>
            <input type="radio" id="reciclador" name="inputTipo" value="False">
            <label for="reciclador">Busca Recicladores e Similares</label><br>
            <input type="radio" id="todos" name="inputTipo" value=None>
            <label for="todos">Busca Todos</label><br>
            </div>
        <div class="col-6 m-auto pt-3 pb-2 text-center"> <!--Barra de busca-->
            <div class="text-center"><label>Busca por Cidade</label></div>
            <input type="text" id="search" name="search" class="form-control" placeholder="Entre com a Cidade..."><br>
        </div>
        </form>
    </div>
    <div class="container-fluid col-12 m-auto pt-3 pb-3 text-center">
        <table class="table table-striped">
          <thead class="thead-light">
            <tr>
              <!--<th scope="col">ID</th>-->
                <th scope="col"><label>Estabelecimento</label></th>
              <th scope="col"><label>Endereço</label></th>
              <th scope="col"><label>Número</label></th>
              <th scope="col"><label>Cidade</label></th>
              <th scope="col"><label>Estado</label></th>
              <th scope="col"><label>Ações</label></th>
            </tr>
          </thead>
          <tbody>
            {% for dbs in db %}
            <tr>
                <!--Os nomes das variáveis são exatamente os mesmos que estão no Banco de Dados, p ex.: dbs.Req_nome -->
                <!--<th>{{dbs.id}}</th>--> <!--Esta variável 'id' vem do Banco de Dados - no caso, SQlite-->
                <td>{{dbs.inputEmpresa}}</td>
                <td>{{dbs.inputAddress}}</td>
                <td>{{dbs.inputNumber}}</td>
                <td>{{dbs.inputCity}}</td>
                <td>{{dbs.inputEstado}}</td>
                <td>
                    <a href="/view/{{dbs.id}}" class="btn btn-info" ><label>Ver</label></a>
                    <a href="/edit/{{dbs.id}}" class="btn btn-primary"><label>Editar</label></a>
                    <a href="/delete/{{dbs.id}}" class="btn btn-danger btnDel"><label>Deletar</label></a>
                </td>
            </tr>
                {% endfor %}
          </tbody>
        </table>
    </div>

    <div class="container-fluid row d-flex justify-content-center">
        <div class="pagination" > <!-- Cria paginação do DB na página inicial-->
            {% if db.has_previous %} <!--Verifica se existe registro anterior-->
                <a href="?page={{db.previous_page_number}}"><label><-Anterior__</label></a> <!--Se existe página anterior, referencia seu caminho no link 'page'-->
            {% endif %}

            {{db.number}} <!-- mostra o número da página atual -->

            {% if db.has_next %} <!-- Se existe página posterior, referencia seu caminho no link 'page'-->
                <a href="?page={{db.next_page_number}}"><label>__Posterior-></label></a>
            {% endif %}
        </div>
    </div>

    {% load static %}
    <script src="{% static 'javascript.js' %}"></script>
  </div>
</div>
</body>
</html>

pji2app/templates/view.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Visualizar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container col-12">
  <div class="jumbotron">
<div class="col-8 m-auto pt-2 pb-2 text-center">
      <h1>Visualização detalhada</h1>
  </div>

  <div class="col-8 m-auto pt-3 pb-2 text-center">
      <a href="/" class="btn btn-info">Voltar</a>
  </div>

  <div class="col-12 m-auto pt-4 pb-2 text-center">
      <table class="table table-striped">
          <thead class="thead-light">
          <tr>
              <td>
                  <strong>ID: </strong>{{db.id}}</td>
              <td>
                  <strong>Estabelecimento: </strong>{{db.inputEmpresa}}</td>
              <td>
                  <strong>CNPJ: </strong>{{db.inputCNPJ}}</td>
              <td>
                  <strong>Email: </strong>{{db.inputEmail}}</td>
          </tr>
          <tr>
              <td>
                  <strong>Telefone: </strong>{{db.inputTel}}</td>
              <td>
                  <strong>Celular: </strong>{{db.inputCel}}</td>
          </tr>
          <tr>
              <td>
                  <strong>Endereço: </strong>{{db.inputAddress}}</td>
              <td>
                  <strong>Número: </strong>{{db.inputNumber}}</td>
              <td>
                  <strong>Complemento: </strong>{{db.inputAddress2}}</td>
          </tr>
          <tr>
              <td>
                  <strong>CEP: </strong>{{db.inputCEP}}</td>
              <td>
                  <strong>Cidade: </strong>{{db.inputCity}}</td>
              <td>
                  <strong>Estado: </strong>{{db.inputEstado}}<br></td>
          </tr>
          </thead>
      </table>
  </div>
    <!--div class="col-8 m-auto pt-4 pb-2 text-center">
        <--img src="http://maps.googleapis.com/maps/api/staticmap?center=LAT, LONG&zoom=11&size=250x250">
    </div-->
  </div>
</div>
</body>
</html>